# Generated by Django 6.0.4 on 2026-04-29 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Color')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Hexadecimal')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex')], max_length=10, verbose_name='Género')),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Minorista')),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mayorista')),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio en Oferta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo / Visible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='productos', to='products.categoria', verbose_name='Categorías')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto Base',
                'verbose_name_plural': 'Productos Base',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Doble Extra Large'), ('U', 'Talle Único')], max_length=5, verbose_name='Talle')),
                ('sku', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='SKU / Código de Artículo')),
                ('cantidad_stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (kg)')),
                ('largo_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Largo (cm)')),
                ('ancho_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ancho (cm)')),
                ('alto_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alto (cm)')),
                ('color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='products.color', verbose_name='Color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='products.producto', verbose_name='Producto Base')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('producto', 'talle', 'color')},
            },
        ),
    ]
