# Generated by Django 6.0.4 on 2026-04-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_categoria_padre_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Género')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AddField(
            model_name='producto',
            name='generos',
            field=models.ManyToManyField(related_name='productos', to='products.genero', verbose_name='Géneros'),
        ),
    ]
