# Generated by Django 6.0.4 on 2026-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_genero_remove_producto_genero_producto_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_promocional',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_promocional_mayorista',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Precio en Oferta (mayorista)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_promocional_minoritsta',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Precio en Oferta (minorista)'),
        ),
    ]
