# Generated by Django 6.0.4 on 2026-04-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_promocional_minoritsta',
            new_name='precio_promocional_minorista',
        ),
    ]
