# Generated by Django 6.0.4 on 2026-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_precio_promocional_minoritsta_producto_precio_promocional_minorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='talle',
            field=models.CharField(max_length=5, verbose_name='Talle'),
        ),
    ]
