# Generated by Django 6.0.4 on 2026-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='generos/', verbose_name='Imagen del Género'),
        ),
    ]
