# Generated by Django 6.0.4 on 2026-05-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_costo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('envio', 'Envío a domicilio'), ('retiro', 'Retiro en local')], default='envio', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria (Descuento)'), ('mercadopago', 'MercadoPago')], default='transferencia', max_length=20),
        ),
    ]
