# Generated by Django 6.0.4 on 2026-05-15 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pedido_descuento_pedido_metodo_entrega_and_more'),
        ('products', '0008_productoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.varianteproducto'),
        ),
    ]
