# Generated by Django 6.0.4 on 2026-05-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_itempedido_variante'),
        ('products', '0008_productoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.varianteproducto'),
        ),
    ]
