# Generated by Django 6.0.4 on 2026-05-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_itempedido_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='nombre_producto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
