# Generated by Django 6.0.4 on 2026-08-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
