# Generated by Django 6.0.4 on 2026-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Senda Distribuidora', max_length=255)),
                ('contact_email', models.EmailField(default='contacto@tuempresa.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Ej: +54 9 11 1234-5678', max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
