# Generated by Django 6.0.4 on 2026-07-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='minimo_compra_mayorista',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Monto mínimo en pesos requerido para pedidos mayoristas.', max_digits=12, verbose_name='Mínimo de compra mayorista'),
        ),
    ]
