# Generated by Django 6.0.4 on 2026-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_minimo_compra_mayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen promocional principal de la portada.', null=True, upload_to='site/', verbose_name='Imagen Principal (Hero)'),
        ),
    ]
