# Generated by Django 6.0.4 on 2026-05-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_transferencia', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de descuento aplicado al subtotal por pagar con transferencia.', max_digits=5)),
                ('datos_bancarios', models.TextField(default='Banco: Banco Nación\nCBU: 0000000000000000000000\nAlias: MI.LOCAL.ROPA\nTitular: Juan Pérez', help_text='Información que verá el cliente para realizar el pago.')),
                ('whatsapp_comprobantes', models.CharField(default='+5491100000000', help_text='Número de WhatsApp donde deben enviar el comprobante.', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuraciones de Pagos',
            },
        ),
    ]
