# Generated by Django 6.0.4 on 2026-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cuit',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Mensaje del cliente mayorista para el administrador.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='es_mayorista',
            field=models.BooleanField(default=True, help_text='Indica que el usuario es mayorista. Se establece automaticamente.'),
        ),
    ]
