# Generated by Django 6.0.4 on 2026-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_cuit_customuser_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='instragram',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='customuser',
            name='razon_social',
            field=models.CharField(blank=True, default='', help_text='Razón social del cliente mayorista', max_length=100),
        ),
    ]
