# Generated by Django 6.0.4 on 2026-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_base', models.DecimalField(decimal_places=2, default=500.0, help_text='Precio inicial.', max_digits=10)),
                ('costo_por_kg_extra', models.DecimalField(decimal_places=2, default=100.0, help_text='Monto que se suma por cada kilogramo total del pedido.', max_digits=10)),
                ('minimo_compra_envio_gratis', models.DecimalField(decimal_places=2, default=50000.0, help_text='Si el total del carrito supera este monto, el envío será $0.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración de Envío',
                'verbose_name_plural': 'Configuraciones de Envío',
            },
        ),
    ]
